esphome:
  name: lilygo-tqt-gas
  friendly_name: LILYGO T-QT Gas Sensor complex
  # on_boot:

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "your_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LILYGO T-QT Gas Sensor complex"
    password: "your_fallback_password"

# Sync time with NTP
time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Kolkata"
    # on_time_sync:
    #   then:
    #     - script.execute: time_update

# I2C Configuration for AHT10
i2c:
  - id: bus_a
    sda: GPIO16
    scl: GPIO48
    scan: true
    # frequency: 10000

# Sensors
sensor:
  # Gas Sensor MQ135 (Analog reading)
  - platform: adc
    pin: GPIO18
    name: "MQ135 Gas Sensor"
    update_interval: 10s
    accuracy_decimals: 2

  # Temperature & Humidity Sensor AHT10
  - platform: aht10
    i2c_id: bus_a
    temperature:
      name: "Air Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
    update_interval: 10s

binary_sensor:
  # Gas sensor Digital Output
  - platform: gpio
    pin: GPIO39
    name: "Gas sensor Digital Output"

  # Flame Sensor
  - platform: gpio
    pin: GPIO35
    name: "Flame Sensor"
